### ISSUE TITLE
Not mark Days to select

### ISSUE THREAD

**Issue by cocuzlan** [nono1526/vue-material-year-calendar#36]
Hi, Today I Download the component but exist a problem.

The problem is: 
I add the respective props in component, similar that: 
**HTML**
              <year-calendar
                  v-model="year"
                  :activeDates.sync="activeDates"
                  prefixClass="helloClass"
                  :activeClass="activeClass"
                  :showYearSelector="false"
                  :hideWeekend="true"
                  lang="es"
                ></year-calendar>
**Script**
import YearCalendar from 'vue-material-year-calendar'
components: {
    YearCalendar
  },
**Data:** 
year: new Date().toISOString().substr(0, 4),
activeDates: [],
activeClass: "helloClass",

**Style**
.helloClass {
   background-color: red;
 }

But never change the color when select, so I decided to inspect the element with devtools in Chrome I saw the class never change, always  the class is: **class: "day"**

After that check the file **MonthCalendar.vue**

In line **169**
if (dayObj.active) oClassList[dayObj.className] = true

**dayObj.className** is not define => undefined

I resolve this way:
Add this lines in the same file (MonthCalendar.vue).
**HTML**
Add
@click="changeActive(dayObj)"
<div
          @mouseover="dragDay(dayObj)"
          @mousedown="mouseDown(dayObj)"
          @click="changeActive(dayObj)" //
          class="day"
          :class="classList(dayObj)">{{ dayObj.value }}</div>
**script**
In part the methods add.
changeActive(i){
      i.active=!i.active
    }

And works again.

**Comment by nono1526** [comment]
HI @cocuzlan 
In `YearCalendar.vue` 
lines 135 `if (dayjs(oDate.date).year() !== this.value) return` (2021 !== '2021' )
If the `year` prop use `String`, then it will not mark any date.

I will fix it and publish new version to npm. Thank you!
