### ISSUE TITLE
建議 github repo 名稱改成正確的「vue-material-year-calendar」

### ISSUE THREAD

**Issue by advancedor96** [nono1526/vue-material-year-calendar#4]
### 建議 github repo 名稱改成正確的「vue-material-year-calendar」
建議 github repo 名稱改成正確的「vue-material-year-calendar」
### 建議 github repo 名稱改成正確的「vue-material-year-calendar」
建議 github repo 名稱改成正確的「vue-material-year-calendar」
### 建議 github repo 名稱改成正確的「vue-material-year-calendar」
建議 github repo 名稱改成正確的「vue-material-year-calendar」
### 建議 github repo 名稱改成正確的「vue-material-year-calendar」
建議 github repo 名稱改成正確的「vue-material-year-calendar」

**Comment by nono1526** [comment]
**已修改成和 npm 一樣的名字 vue-material-year-calendar**

**Comment by nono1526** [comment]
#＃＃ 建議 github repo 名稱改成正確的「vue-material-year-calendar」
