### ISSUE TITLE
date selecting behavior is a bit glitchy

### ISSUE THREAD

**Issue by imrobinized** [nono1526/vue-material-year-calendar#7]
Questions:
1. What would be the reason of performing the toggling behavior in a hover event callback?

https://github.com/nono1526/vue-material-year-calendar/blob/9efa7433fdfe6c21aa6bd6f27ebd31e924d3aa1f/src/components/MonthCalendar.vue#L100-L102

2. You're keeping a `isMouseDown` state. However, the value will be updated by the event callback from **different DOM element**.
Event handlers:
https://github.com/nono1526/vue-material-year-calendar/blob/9efa7433fdfe6c21aa6bd6f27ebd31e924d3aa1f/src/components/MonthCalendar.vue#L103-L109
Mouse down event is triggered by the inner element of `.calendar__day`. But mouse up event is triggered by the wrapper DOM of `MonthCalendar`:
https://github.com/nono1526/vue-material-year-calendar/blob/9efa7433fdfe6c21aa6bd6f27ebd31e924d3aa1f/src/components/MonthCalendar.vue#L3-L13

Those causes the glitchy behav, see the recording http://recordit.co/2diZSzXp1K

According to the screen recording. In certain cases, selecting/unselecting date will select/unselect again. It's because the select/unselect behavior will be perform not only when "mousedown" (clicking on the date), but also on the hover event when `this.isMouseDown` is `true`.

So, this happens:
suppose we have this condition, 15 and 16 were selected
![image](https://user-images.githubusercontent.com/12913401/52908999-6833a900-32bb-11e9-88b7-f2a1861bc172.png)

1. unselect a date by clicking on the overlapped corner of the red icon on date `15`
![image](https://user-images.githubusercontent.com/12913401/52908991-3c182800-32bb-11e9-9931-c3e4fe499161.png)
2. `"mousedown"` triggered, date toggled (unselect 15), set **isMouseDown** to true
3. hover event on date 16 triggered
4. `toggleDay` called (select 16) because `isMouseDown` is true

BTW, the unselect icon is overlapped by date element. You might want to adjust the order (perhaps setting `z-index`).

**Comment by nono1526** [comment]
Hi, imrobinized !
# To question 1: 
The reason that toggling the `this.isMouseDown` state  is that we want the user can multiply toggle dates.

See the screen recording. ![image](https://media.giphy.com/media/x4b08WpEqAocjxoCqT/giphy.gif)
# To question 2: 
When the user click the edge of .day element, `mouseclick` and `mouseover` event both will be fire.

I try to remove .day element's `border-radius`. There does not happen again.

**Comment by advancedor96** [comment]
### 請問樓上兩位都是台灣人嗎？為什麼要用英文溝通呢？

**Comment by nono1526** [comment]
It seems the pseudo icon made this trouble.
1. When user click the overlap of icon and `.day` element.  ![image](https://i.imgur.com/jgeCLnh.png)

2. Icon will be hid. And `mouseover` will be triggered. (This cause Question 2 happen.)

I create pseudo `:after` in advance. This works fine !

code

```css
    &:after
      content ''
      display block
      height: 10px
      width 10px
      position absolute
      top -5px
      right -5px
      border-radius 50%
      z-index: 1
      background-color transparent
    &.calendar--active:after
      background-image url('../assets/baseline-remove_circle-24px.svg')
      background-size 100% 100%
```
